import { Poppins } from "next/font/google";
import "./globals.css";

const poppins = Poppins({
  subsets: ["latin"], // Include subsets like 'latin' or 'latin-ext'
  weight: ["400", "700"], // Specify font weights (e.g., 400 for regular, 700 for bold)
  variable: "--font-poppins", // CSS variable name
});

export const metadata = {
  title: "Navicode",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={`${poppins.variable} antialiased`}>
        {children}
      </body>
    </html>
  );
}
